name: 财税早报
on:
  schedule:
    - cron: '0 1 * * *'  # UTC时间1点=北京时间9点
jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - name: 下载代码
        uses: actions/checkout@v4
      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install requests beautifulsoup4
      - name: 运行机器人
        run: |
          python3 news_bot.py
